# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "dd7cfa16-9f62-4836-bc8b-2800831f9cec"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "59a9496fd34385ea4a5091fb984ec644f5e7bb9b",
    build_secret: "3da63b4928e12c1d54bf572fc9bab3e6f887a2a47c086005e34dd6a3558b0964"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
